/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Janelas;

import Entidades.Taxista;
import java.awt.Toolkit;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import javax.swing.JOptionPane;

/**
 *
 * @author Ramon Honorio
 */
public class JanelaTaxistaPrincipal extends javax.swing.JFrame {
    JanelaCadastroCliente cad;
    Taxista taxista;
    
    /**
     * Creates new form Principal
     */
    public JanelaTaxistaPrincipal() {
        initComponents();
        
        // Inserir icone :D
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/img/botoes/icone.png")));
        
        cad = new JanelaCadastroCliente();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblNomeTaxista = new javax.swing.JLabel();
        btNovaPesquisa = new javax.swing.JButton();
        btSair = new javax.swing.JButton();
        lblTexto1 = new javax.swing.JLabel();
        lblTexto2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImages(null);
        setResizable(false);

        lblNomeTaxista.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblNomeTaxista.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNomeTaxista.setText("Olá, (nome do taxista)!");

        btNovaPesquisa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/botoes/nova pesquisa naos.png"))); // NOI18N
        btNovaPesquisa.setText("Nova pesquisa");
        btNovaPesquisa.setContentAreaFilled(false);
        btNovaPesquisa.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btNovaPesquisa.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/img/botoes/nova pesquisa rollover.png"))); // NOI18N
        btNovaPesquisa.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btNovaPesquisa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btNovaPesquisaActionPerformed(evt);
            }
        });

        btSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/botoes/logout.png"))); // NOI18N
        btSair.setText("Sair");
        btSair.setContentAreaFilled(false);
        btSair.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btSair.setIconTextGap(0);
        btSair.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/img/botoes/logout rollover.png"))); // NOI18N
        btSair.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSairActionPerformed(evt);
            }
        });

        lblTexto1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblTexto1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTexto1.setText("Bem vindo ao sistema de pesquisa de satisfação Raikon.");

        lblTexto2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblTexto2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTexto2.setText("O que deseja fazer?");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(btNovaPesquisa)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btSair))
                    .addComponent(lblNomeTaxista, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblTexto1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 416, Short.MAX_VALUE)
                    .addComponent(lblTexto2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblNomeTaxista)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblTexto1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblTexto2)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btNovaPesquisa)
                    .addComponent(btSair))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btNovaPesquisaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btNovaPesquisaActionPerformed
        // TODO add your handling code here:
        novoCadastro();
    }//GEN-LAST:event_btNovaPesquisaActionPerformed

    private void btSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSairActionPerformed
        janelaFechamento();
    }//GEN-LAST:event_btSairActionPerformed
    
    public void novoCadastro(){
        cad.dispose();
        cad = new JanelaCadastroCliente();
        cad.setVisible(true);
        cad.taxista = new Taxista(taxista);
    }
    
    public void fechando(){
        this.addWindowListener(new WindowAdapter(){
            public void windowClosing(WindowEvent e){
                janelaFechamento();
            }
        });
    }
    
    public void janelaFechamento(){
        String[] op = { "Sim", "Não" };
        int escolha = JOptionPane.showOptionDialog(this, "Tem certeza que deseja sair?", "Sair", 
                JOptionPane.YES_OPTION, JOptionPane.QUESTION_MESSAGE, null, op, null);
        
            if(escolha == 0)
                System.exit(0);
    }
    
    public void arrumarTitulo(){
        lblNomeTaxista.setText("Olá, "+taxista.getNome()+"!");
    }

    public void executar(){
        this.setVisible(true);
        this.fechando();
    }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JanelaTaxistaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JanelaTaxistaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JanelaTaxistaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JanelaTaxistaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                JanelaTaxistaPrincipal tp = new JanelaTaxistaPrincipal();
                tp.executar();
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btNovaPesquisa;
    private javax.swing.JButton btSair;
    private javax.swing.JLabel lblNomeTaxista;
    private javax.swing.JLabel lblTexto1;
    private javax.swing.JLabel lblTexto2;
    // End of variables declaration//GEN-END:variables
}
